<a href="https://colab.research.google.com/github/REPANAJYOTHIPRAKASH629/MACHINE_LEARNING/blob/main/ML_EXP_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# One-hot encode the target variable
enc = OneHotEncoder()
y = enc.fit_transform(y.reshape(-1, 1)).toarray()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Neural Network class
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.weights_input_hidden = np.random.rand(self.input_size, self.hidden_size)
        self.bias_input_hidden = np.random.rand(1, self.hidden_size)
        self.weights_hidden_output = np.random.rand(self.hidden_size, self.output_size)
        self.bias_hidden_output = np.random.rand(1, self.output_size)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_input_hidden
        self.hidden_output = self.sigmoid(self.hidden_input)
        self.output_layer_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_hidden_output
        self.predicted_output = self.sigmoid(self.output_layer_input)
        return self.predicted_output

    def backward(self, X, y, output, learning_rate):
        self.error = y - output
        delta_output = self.error * self.sigmoid_derivative(output)
        self.hidden_layer_error = delta_output.dot(self.weights_hidden_output.T)
        delta_hidden = self.hidden_layer_error * self.sigmoid_derivative(self.hidden_output)
        self.weights_hidden_output += self.hidden_output.T.dot(delta_output) * learning_rate
        self.bias_hidden_output += np.sum(delta_output, axis=0, keepdims=True) * learning_rate
        self.weights_input_hidden += X.T.dot(delta_hidden) * learning_rate
        self.bias_input_hidden += np.sum(delta_hidden, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output, learning_rate)
            if epoch % 100 == 0:
                loss = np.mean(np.square(y - output))
                print(f"Epoch {epoch}: Loss - {loss}")

# Initialize neural network
nn = NeuralNetwork(input_size=X.shape[1], hidden_size=4, output_size=y.shape[1])

# Train the network
nn.train(X_train, y_train, epochs=1000, learning_rate=0.1)

# Test the trained network
predicted_output = nn.forward(X_test)
print("Predicted Output on Test Data:")
print(predicted_output)


Epoch 0: Loss - 0.585550057892509
Epoch 100: Loss - 0.3110373679982162
Epoch 200: Loss - 0.12868652680069972
Epoch 300: Loss - 0.12763854982131906
Epoch 400: Loss - 0.1273065165251276
Epoch 500: Loss - 0.12714331007260116
Epoch 600: Loss - 0.12704501452126285
Epoch 700: Loss - 0.12697648894462252
Epoch 800: Loss - 0.1269196084552261
Epoch 900: Loss - 0.1268607582892578
Predicted Output on Test Data:
[[0.01182422 0.3312338  0.68373958]
 [0.9817065  0.00795597 0.01219296]
 [0.01179045 0.33152506 0.68411831]
 [0.01184249 0.33106692 0.68353264]
 [0.01182385 0.33122503 0.68374058]
 [0.98167365 0.00796691 0.01220874]
 [0.01455361 0.308822   0.65515432]
 [0.01179372 0.33150052 0.68408228]
 [0.01179893 0.33147272 0.6840286 ]
 [0.01242889 0.32579903 0.67700269]
 [0.01179535 0.33148859 0.68406443]
 [0.98159381 0.00799576 0.01224921]
 [0.98170025 0.00796172 0.01219809]
 [0.9816028  0.0079903  0.01224315]
 [0.98168788 0.00796572 0.01220383]
 [0.01186416 0.33085532 0.68328381]
 [0.01179005 0.331534